// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiHDFykv99zp3KbqrCee-YqouGH_F3F4k',
    appId: '1:995065301015:web:bccba0b26b8a27d90db452',
    messagingSenderId: '995065301015',
    projectId: 'lostpets-36381',
    authDomain: 'lostpets-36381.firebaseapp.com',
    storageBucket: 'lostpets-36381.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoOGyByf_sY7-9z0QhorM1MA_ROquaIao',
    appId: '1:995065301015:android:a7030fbdc97692460db452',
    messagingSenderId: '995065301015',
    projectId: 'lostpets-36381',
    storageBucket: 'lostpets-36381.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGjMI1ey7qEE3U1CqTKHiyGiGbkI5lpmc',
    appId: '1:995065301015:ios:fac351f937accd4e0db452',
    messagingSenderId: '995065301015',
    projectId: 'lostpets-36381',
    storageBucket: 'lostpets-36381.firebasestorage.app',
    iosBundleId: 'com.nodamngoodstudios.tempoct2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGjMI1ey7qEE3U1CqTKHiyGiGbkI5lpmc',
    appId: '1:995065301015:ios:fac351f937accd4e0db452',
    messagingSenderId: '995065301015',
    projectId: 'lostpets-36381',
    storageBucket: 'lostpets-36381.firebasestorage.app',
    iosBundleId: 'com.nodamngoodstudios.tempoct2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiHDFykv99zp3KbqrCee-YqouGH_F3F4k',
    appId: '1:995065301015:web:82d7f8e4c549ed0d0db452',
    messagingSenderId: '995065301015',
    projectId: 'lostpets-36381',
    authDomain: 'lostpets-36381.firebaseapp.com',
    storageBucket: 'lostpets-36381.firebasestorage.app',
  );
}
